use ProjectMahoraga

-- Insert data into genre table
INSERT INTO genre (aniid, genre)
VALUES
(1, 'Shounen'),
(1, 'Action'),
(1, 'Adventure'),
(1, 'Fantasy'),
(2, 'Shounen'),
(2, 'Action'),
(2, 'Adventure'),
(2, 'Fantasy'),
(3, 'Shounen'),
(3, 'Action'),
(3, 'Adventure'),
(4, 'Shounen'),
(4, 'Action'),
(4, 'Dark Fantasy'),
(5, 'Psychological'),
(5, 'Mystery'),
(5, 'Thriller'),
(6, 'Shounen'),
(6, 'Adventure'),
(6, 'Fantasy'),
(6, 'Science Fiction'),
(7, 'Shounen'),
(7, 'Action'),
(7, 'Adventure'),
(7, 'Super Power'),
(8, 'Adventure'),
(8, 'Action'),
(8, 'Fantasy'),
(8, 'Romance'),
(9, 'Shounen'),
(9, 'Action'),
(9, 'Adventure'),
(9, 'Fantasy'),
(10, 'Shounen'),
(10, 'Action'),
(10, 'Adventure'),
(10, 'Dark Fantasy'),
(11, 'Psychological'),
(11, 'Horror'),
(11, 'Action'),
(12, 'Action'),
(12, 'Comedy'),
(12, 'Super Power'),
(12, 'Parody'),
(13, 'Action'),
(13, 'Adventure'),
(13, 'Science Fiction'),
(13, 'Space'),
(14, 'Mecha'),
(14, 'Psychological'),
(14, 'Science Fiction'),
(14, 'Post-Apocalyptic'),
(15, 'Thriller'),
(15, 'Science Fiction'),
(15, 'Time Travel'),
(16, 'Action'),
(16, 'Adventure'),
(16, 'Fantasy'),
(17, 'Shounen'),
(17, 'Action'),
(17, 'Supernatural'),
(18, 'Shounen'),
(18, 'Action'),
(18, 'Adventure'),
(18, 'Magic'),
(19, 'Action'),
(19, 'Drama'),
(19, 'Horror'),
(19, 'Dark Fantasy'),
(20, 'Shounen'),
(20, 'Action'),
(20, 'Adventure'),
(20, 'Science Fiction'),
(21, 'Shounen'),
(21, 'Action'),
(21, 'Adventure'),
(22, 'Comedy'),
(22, 'Parody'),
(22, 'School'),
(23, 'Shounen'),
(23, 'Action'),
(23, 'Adventure'),
(23, 'Comedy'),
(24, 'Shounen'),
(24, 'Action'),
(24, 'Adventure'),
(24, 'Science Fiction'),
(25, 'Action'),
(25, 'Adventure'),
(25, 'Romance'),
(25, 'Fantasy'),
(26, 'Action'),
(26, 'Adventure'),
(26, 'Fantasy'),
(26, 'Super Power'),
(27, 'Action'),
(27, 'Adventure'),
(27, 'Fantasy'),
(27, 'Game'),
(28, 'Action'),
(28, 'Adventure'),
(28, 'Fantasy'),
(28, 'Super Power'),
(29, 'Action'),
(29, 'Adventure'),
(29, 'Fantasy'),
(29, 'Mystery'),
(30, 'Action'),
(30, 'Adventure'),
(30, 'Super Power'),
(30, 'Fantasy');

select * from genre